stages:
  - trigger_clients_pipelines

trigger_web:
  stage: trigger_clients_pipelines
  trigger:
    project: "binarywizards/s5-binarywizards-web"
    branch: "devops"  
    strategy: depend

trigger_mobile:
  stage: trigger_clients_pipelines
  trigger:
    project: "binarywizards/s5-binarywizards-mobile"
    branch: "devops"
    strategy: depend