image: node:latest

test:
  script:
    - npm install
    - npm i -g create-env
    - touch .env
    - npx create-env --env-file .env --env-prefix TEST_
    - npx prisma db push
    - npx prisma generate
    - npm test --coverage --coverageDirectory=coverage --coverageProvider=babel --outputFile=coverage/test-results.xml
  artifacts:
    when: always
    reports:
      junit: coverage/test-results.xml
    paths:
      - coverage/test-results.xml
  allow_failure: true

build:
  needs:
    - test
  script:
    - echo "Build process started..."
    - echo "Build process completed."
  artifacts:
    when: on_success

deploy:
  needs:
    - build
  script:
    - echo "Deploy process started..."
    - echo "Deploy process completed."


trigger_web:
  needs:
    - test
  trigger:
    project: "binarywizards/s5-binarywizards-web"
    branch: "main"  
    strategy: depend

trigger_mobile:
  needs:
    - test
  trigger:
    project: "binarywizards/s5-binarywizards-mobile"
    branch: "main"
    strategy: depend
